version: "3"
services:
  server:
    restart: always
    ports:
      - "3000:3000"
    build:
      context: ./server
      dockerfile: js.Dockerfile
  
  client:
    network_mode: host
    depends_on: 
      - "server"
    build:
      context: ./client
      dockerfile: py.Dockerfile
