version: "3"
services:
  js:
    restart: always
    ports:
      - "3000:3000"
    build:
      context: ./javascript
      dockerfile: js.Dockerfile
  cpp:
    build:
      context: ./cpp
      dockerfile: cpp.Dockerfile
  python:
    build:
      context: ./python
      dockerfile: py.Dockerfile
